import { SafeUrl } from '@angular/platform-browser';

/** Page rendering result structure data */
export interface RenderedPage {
    /** Raw base64 string for Image */
    RawBase64: string;

    /** SafeUrl, If you need to directly output the baseurl of the image in the template view, use this property */
    SafeUrl: SafeUrl;

    /** A picture object generated by the current page context */
    Image: HTMLImageElement;
}
